# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-21 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20170321_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='inc',
            field=models.SmallIntegerField(blank=True, max_length=3, null=True),
        ),
    ]
