# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-21 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20170321_1136'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='inc',
        ),
    ]
