# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('img', models.CharField(max_length=500, verbose_name='Аватарка')),
                ('file', models.FileField(upload_to='/media/')),
                ('file2', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('sort', models.SmallIntegerField(default=100, verbose_name='Сортировка')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
        ),
        migrations.AddField(
            model_name='bloger',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.Category', verbose_name='Катагория'),
        ),
    ]
