# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloger',
            options={'verbose_name': 'Блогер', 'verbose_name_plural': 'Блогеры'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='bloger',
            name='file',
        ),
        migrations.RemoveField(
            model_name='bloger',
            name='file2',
        ),
        migrations.AddField(
            model_name='bloger',
            name='is_favorites',
            field=models.BooleanField(default=False, help_text='для избранного !', verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='category/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='bloger',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='youtube.Category', verbose_name='Катагория'),
        ),
        migrations.AlterField(
            model_name='bloger',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='bloger/', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort',
            field=models.SmallIntegerField(blank=True, default=100, null=True, verbose_name='Сортировка'),
        ),
    ]
