# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloger',
            name='file2',
        ),
        migrations.AlterField(
            model_name='bloger',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
