# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-11 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_main_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='comment',
        ),
    ]
