# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20170323_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloger',
            name='file',
        ),
        migrations.AlterField(
            model_name='bloger',
            name='img',
            field=models.FileField(upload_to='media/', verbose_name='Аватарка'),
        ),
    ]
