# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-11 08:20
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_remove_main_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
