# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_auto_20170323_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='category/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='bloger',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='youtube.Category', verbose_name='Катагория'),
        ),
        migrations.AlterField(
            model_name='bloger',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='bloger/', verbose_name='Аватарка'),
        ),
    ]
