# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-11 12:42
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_main_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='tiny',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
