# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_main_tiny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='tiny',
            field=models.TextField(),
        ),
    ]
