# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_auto_20170324_1206'),
        ('youtube', '0002_auto_20170324_1305'),
    ]

    operations = [
    ]
