# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloger',
            name='category',
        ),
        migrations.DeleteModel(
            name='Bloger',
        ),
    ]
