# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_auto_20170324_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('img', models.FileField(blank=True, null=True, upload_to='bloger/', verbose_name='Аватарка')),
                ('is_favorites', models.BooleanField(default=False, help_text='для избранного !', verbose_name='Избранное')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='youtube.Category', verbose_name='Катагория')),
            ],
            options={
                'verbose_name_plural': 'Блогеры',
                'verbose_name': 'Блогер',
            },
        ),
    ]
