# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0009_bloger_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='slug',
            field=models.SlugField(default='default'),
        ),
    ]
