# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0011_auto_20170331_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='default', null=True),
        ),
    ]
